version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning

  infra:
    build:
      dockerfile: Dockerfile
      
volumes:  
  redis-data:
    driver: local
      